// Code generated by scripts/build.sh. DO NOT EDIT.

package phpwasm

// PHPVersion is the php-src release the binaries are built from.
const PHPVersion = "8.6.0RC3"

// CLIDigest and CGIDigest identify the binaries, without decompressing
// them. A host may keep CLI() or CGI() on disk under its digest, since
// decompressing takes longer than reading.
const (
	CLIDigest = "2c8dbaca0449b2f5"
	CGIDigest = "43d31337a41bcc6a"
)
