// Code generated by scripts/build.sh. DO NOT EDIT.

package phpwasm

// PHPVersion is the php-src release the binaries are built from.
const PHPVersion = "8.6.0RC3"

// CLIDigest and CGIDigest identify the binaries, without decompressing
// them. A host may keep CLI() or CGI() on disk under its digest, since
// decompressing takes longer than reading.
const (
	CLIDigest = "10d7e9d2c4ae44ff"
	CGIDigest = "5e119dde5ec0b5d1"
)
